---
- name: reload apache
  service: name=apache2 state=reloaded
  become: True

- name: restart apache
  service: name=apache2 state=restarted
  become: True

- name: restart mysql
  service: name=mysql state=restarted
  become: True
