---

- name: required packages
  apt:
    name: python-mysqldb
  become: True

- name: create readonly acess to monarc common
  mysql_user:
    name: "{{ item.value.name }}"
    password: "{{ item.value.mysql_password }}"
    priv: "monarc_common.*:SELECT"
    config_file: /etc/mysql/debian.cnf
  with_dict: "{{ dict(groups['dev'] | map('extract',hostvars,'clients') | map('dictsort') | sum(start=[]) | list) }}"
  become: True
  #with_dict:
  #with_items:
  #- "{{ data| json_query(hostvars.client1.dev.monarc.lc1.conostix.com']['clients'] }}"

- name: create spool directory
  file: name=/var/spool/monarc owner=www-data state=directory
  become: True

- name: create temp directory for parsing new clients
  file: name=/var/tmp/monarc/created recurse=True state=directory owner=www-data
  become: True

- name: create temp directory for parsing deleted clients
  file: name=/var/tmp/monarc/deleted recurse=True state=directory owner=www-data
  become: True

- name: install cat script for new clients
  copy: src=new_monarc_clients.sh dest=/usr/local/bin/new_monarc_clients.sh mode=0755
  become: True

- name: install cat script for deleted clients
  copy: src=del_monarc_clients.sh dest=/usr/local/bin/del_monarc_clients.sh mode=0755
  become: True
