---

- name: install php7 and nodejs packages
  apt:
    name: "{{ item }}"
    update_cache: True
  with_items:
    - apache2
    - libapache2-mod-php
    - mariadb-server
    - php
    - php-cli
    - php-mbstring
    - php-xml
    - php-mysql
    - php-zip
    - php-mcrypt
    - php-intl
    - php-imagick
    - nodejs
    - npm
    - python-mysqldb
    - gettext
  become: True

- name: monarc directory
  file:
    path: /var/lib/monarc
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  become: True

- name: install grunt
  command: "npm install -g grunt-cli"
  become: True

- name: create symlink to /usr/bin/node
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
  become: True
